<a href="https://colab.research.google.com/github/rohinishimpatwar/The-NLP-News-Sentiment-Trading-Strategy/blob/master/NLP/Part3_Sentiment_Model_Vader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

%pwd  #look at the current work dir
%cd Sentiment Labeling
%pwd

df3 = pd.read_csv('news_with_cleaned_text.csv')
#pd.options.display.max_colwidth = 10000000
df3.head(10)

C:\Users\Daria-Y\Desktop\DS4A_workspace\DATASETS\Sentiment Labeling

,Unnamed: 0,title,text,Company,Industry,text_nwords,log_nword,text_no_stopwords
0,297858,Trader sees a rally ahead for bonds,Trader sees a rally ahead for bonds 1 Hour Ago,"['E*Trade', '']",['Financials'],10,2.302585,trader sees rally ahead hour ago
1,299381,White House addresses AT&T payment to Michael ...,White House addresses AT&T payment to Michael ...,"['AT&T', '']",['Communication Services'],13,2.564949,addresses payment hours ago
2,302775,BRIEF-Boston Scientific Closes NxThera Acquisi...,April 30 (Reuters) - Boston Scientific Corp:\n...,"['Boston Scientific', '']",['Health Care'],25,3.218876,reuters scientific corp scientific closes nxth...
3,302541,GE to merge transportation unit with Wabtec,GE to merge transportation unit with Wabtec 50...,"['General Electric', '']",['Industrials'],30,3.401197,ge merge transportation unit wabtec mins ago c...
4,302639,BRIEF-MetLife To Provide Pension Benefits To A...,May 8 (Reuters) - MetLife Inc:\n* METLIFE TO P...,"['MetLife Inc.', '']",['Financials'],31,3.433987,reuters metlife metlife provide pension benefi...
5,299201,BRIEF-Mondelēz Declares Regular Quarterly Divi...,May 16 (Reuters) - Mondelez International Inc:...,"['Mondelez International', '']",['Consumer Staples'],31,3.433987,reuters mondelez international mondelēz intern...
6,298226,Markets poised to open higher after US Iran de...,Markets poised to open higher after US Iran de...,"['E*Trade', '']",['Financials'],31,3.433987,markets poised open higher iran decision hours...
7,299893,BRIEF-Gap Inc Announces Q1 Dividend,May 23 (Reuters) - Gap Inc:\n* ANNOUNCES SECON...,"['Gap Inc.', '']",['Consumer Discretionary'],32,3.465736,reuters gap announces dividend sets dividend s...
8,300783,BRIEF-GE Hitachi Announces Dominion Energy As ...,May 21 (Reuters) - General Electric Co:\n* GE ...,"['General Electric', '']",['Industrials'],32,3.465736,reuters general electric ge hitachi announces ...
9,302004,BRIEF-Constellation Brands Promotes Jim Sabia ...,May 22 (Reuters) - Constellation Brands Inc:\n...,"['Constellation Brands', '']",['Consumer Staples'],33,3.496508,reuters constellation brands constellation bra...

In [0]:
# NLTK VADER for sentiment analysis
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('stopwords')
nltk.download('vader_lexicon')

# New words and values
new_words = {
    'crushes': 10,
    'beats': 5,
    'misses': -5,
    'trouble': -10,
    'falls': -100,
}
# Instantiate the sentiment intensity analyzer with the existing lexicon
vader = SentimentIntensityAnalyzer()
# Update the lexicon
vader.lexicon.update(new_words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Daria-Y\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Daria-Y\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [0]:

scored_news = df3
# Iterate through the headlines and get the polarity scores
scores = [vader.polarity_scores(text_no_stopwords) for text_no_stopwords in scored_news.text_no_stopwords.values]
# Convert the list of dicts into a DataFrame
scores_df = pd.DataFrame(scores)
# Join the DataFrames
scored_news = pd.concat([scored_news, scores_df], axis=1)

In [0]:
pd.options.display.max_colwidth = 10000000
scored_news.head(3)

,Unnamed: 0,title,text,Company,Industry,text_nwords,log_nword,text_no_stopwords,compound,neg,neu,pos
0,297858,Trader sees a rally ahead for bonds,Trader sees a rally ahead for bonds 1 Hour Ago,"['E*Trade', '']",['Financials'],10,2.302585,trader sees rally ahead hour ago,0.0,0.0,1.0,0.0
1,299381,White House addresses AT&T payment to Michael Cohen,White House addresses AT&T payment to Michael Cohen 17 Hours Ago,"['AT&T', '']",['Communication Services'],13,2.564949,addresses payment hours ago,0.0,0.0,1.0,0.0
2,302775,BRIEF-Boston Scientific Closes NxThera Acquisition,April 30 (Reuters) - Boston Scientific Corp:\n* BOSTON SCIENTIFIC CLOSES NXTHERA ACQUISITION Source text for Eikon: Further company coverage:\n,"['Boston Scientific', '']",['Health Care'],25,3.218876,reuters scientific corp scientific closes nxthera acquisition source text eikon company coverage,0.0,0.0,1.0,0.0

In [0]:
%cd C:\\Users\\Daria-Y\\Desktop\\DS4A_workspace\\DATASETS
%pwd

C:\Users\Daria-Y\Desktop\DS4A_workspace\DATASETS

'C:\\Users\\Daria-Y\\Desktop\\DS4A_workspace\\DATASETS'

In [0]:
test_df = pd.read_csv('news_with_all_labels.csv', index_col=[0])
pd.options.display.max_colwidth = 1000
test_df.head(5)

,Unnamed: 0.1,published,title,text,word_num,Company,company_0,company_1,company_2,company_3,...,company_6,company_7,Industry,industry_0,industry_1,industry_2,industry_3,industry_4,industry_5,industry_6
296244,296244,2018-05-10T19:10:00.000+03:00,JPMorgan Applies to Launch Joint-Venture Brokerage in China,"JPMorgan Chase & Co. is seeking approval from a Chinese regulator to launch a joint-venture brokerage in the country, becoming the latest bank to explore the opportunity after Chinese authorities loosened rules on foreign firms controlling such ventures.\nJ.P. Morgan Broking (Hong Kong) Ltd., a unit of the company, has applied to seek a 51% stake in a joint-venture brokerage in China, said Gao Li, a spokeswoman for the China Securities Regulatory Commission, on Thursday. The CSRC will review the application, the spokeswoman... To Read the Full Story Subscribe Sign In",90,"['JPMorgan Chase & Co.', '']",JPMorgan Chase & Co.,NaN,NaN,NaN,...,NaN,NaN,['Financials'],Financials,NaN,NaN,NaN,NaN,NaN,NaN
296257,296257,2018-05-26T16:28:00.000+03:00,Should Trump Care about Xi’s “Made in China 2025” Plan?,"By Clay Chandler 9:28 AM EDT\nIt’s on! It’s off! It’s on again! Press reports about Donald Trump’s relationship with North Korean dictator Kim Jong-un are starting to resemble tabloid coverage of Justin Bieber and Selena Gomez. All the drama—plus nuclear weapons!\nIn the latest twist, Trump now says his June 12 summit with Kim in Singapore, which he canceled abruptly via petulant letter , might happen after all . One sign that the dialogue with North Korea is back on track: Kim held an unexpected meeting with South Korean president Moon Jae-in on the north side of the Demilitarized Zone today.\nThe U.S. president continues to suggest that he doesn’t think he can get a denuclearization agreement from Kim without the cooperation of Chinese president Xi Jinping. So for now, the fact that a North Korea deal remains in play means that Trump’s trade war with China remains “ on hold ” and Trump remains committed to his promise to Xi to undo Commerce Department sanctions that would put Chi...",1324,"['E*Trade', '']",E*Trade,NaN,NaN,NaN,...,NaN,NaN,['Financials'],Financials,NaN,NaN,NaN,NaN,NaN,NaN
296260,296260,2018-05-03T23:00:00.000+03:00,Linda Forry Named Eversource Trustee,"HARTFORD, Conn. & BOSTON--(BUSINESS WIRE)-- Eversource Energy today announced the election of Linda Dorcena Forry to its board of trustees, effective May 2, 2018. Forry is Vice President of Diversity, Inclusion and Community Relations, Northeast Region, at Suffolk Construction, where she is responsible for strengthening its diversity and inclusion program, developing long-term talent, and ensuring compliance with local workforce requirements.\nThis press release features multimedia. View the full release here: https://www.businesswire.com/news/home/20180503006426/en/\nLinda Dorcena Forry was elected to the Board of Trustees of Eversource Energy. (Photo: Business Wire).\nPrior to joining Suffolk Construction, Forry served in the Massachusetts State Senate where she was appointed to leadership as Assistant Majority Whip. She was the first woman and person of color elected to represent the First Suffolk Senate District, which includes Dorchester, Hyde Park, Mattapan and South Boston.\...",444,"['Eversource Energy', '']",Eversource Energy,NaN,NaN,NaN,...,NaN,NaN,['Utilities'],Utilities,NaN,NaN,NaN,NaN,NaN,NaN
296267,296267,2018-05-10T16:00:00.000+03:00,"P&F Industries, Inc. Reports For The Three Months Ended March 31,","MELVILLE, N.Y., May 10, 2018 /PRNewswire/ -- P&F Industries, Inc. (NASDAQ: PFIN) today announced its results from operations for the three-month period ended March 31, 2018. The Company is reporting revenue of $15,742,000, compared to $13,216,000, for the same period in 2017. Additionally, the Company is reporting net income before taxes of $88,000, compared to a loss of $84,000, for the first quarter in 2017. After giving effect to income tax expense of $23,000, the Company is reporting net income for the three-month period ended March 31, 2018 of $65,000. During the first quarter of 2017, the Company recorded a tax benefit of $24,000, and a $60,000 loss after taxes.\nRichard Horowitz, the Company's Chairman of the Board, Chief Executive Officer and President commented, ""I am pleased to report that our first quarter 2018 revenue is more than 19% greater than the same period a year ago, with net income increasing $125,000. The acquisition of the business assets of Jiffy Air Tool, I...",4281,"['E*Trade', 'Home Depot', 'Stanley Black & Decker', '']",E*Trade,Home Depot,Stanley Black & Decker,NaN,...,NaN,NaN,"['Financials', 'Consumer Discretionary', 'Industrials']",Financials,Consumer Discretionary,Industrials,NaN,NaN,NaN,NaN
296274,296274,2018-05-01T13:16:00.000+03:00,BP flags possible dividend boost as profits surge,"May 1, 2018 / 6:13 AM / Updated an hour ago BP flags possible dividend boost as profits surge Ron Bousso 4 Min Read\nLONDON (Reuters) - BP held out the prospect of a first dividend increase since 2014 on Tuesday, after first-quarter profits beat forecasts thanks to rising oil and gas prices and production. The logo of BP is seen at a petrol station in Kloten, Switzerland October 3, 2017. REUTERS/Arnd Wiegmann\nChief Financial Officer Brian Gilvary said the London-listed company might consider raising the dividend later this year if oil prices remain near current levels and debt declines.\nIn the first three months of 2018, however, BP’s debt rose to $40 billion due to the settlement of more lawsuits over the deadly 2010 Deepwater Horizon spill in the Gulf of Mexico which has cost it more than $65 billion.\nA nearly 25 percent rise in oil prices over the past year to over $70 a barrel has lifted revenue for oil companies, shifting investors’ focus to how much cash they can generate ...",671,"['Morgan Stanley', '']",Morgan Stanley,NaN,NaN,NaN,...,NaN,NaN,['Financials'],Financials,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
test_date = test_df[['Unnamed: 0.1', 'published']]
test_date

        Unnamed: 0.1                      published
296244        296244  2018-05-10T19:10:00.000+03:00
296257        296257  2018-05-26T16:28:00.000+03:00
296260        296260  2018-05-03T23:00:00.000+03:00
296267        296267  2018-05-10T16:00:00.000+03:00
296274        296274  2018-05-01T13:16:00.000+03:00
296275        296275  2018-05-29T00:50:00.000+03:00
296285        296285  2018-05-04T01:04:00.000+03:00
296295        296295  2018-05-08T15:30:00.000+03:00
296296        296296  2018-05-07T23:19:00.000+03:00
296301        296301  2018-05-17T19:21:00.000+03:00
296342        296342  2018-05-11T03:00:00.000+03:00
296347        296347  2018-05-24T19:14:00.000+03:00
296354        296354  2018-05-17T15:00:00.000+03:00
296363        296363  2018-05-21T22:35:00.000+03:00
296369        296369  2018-05-01T03:00:00.000+03:00
296374        296374  2018-05-08T03:00:00.000+03:00
296376        296376  2018-05-24T19:21:00.000+03:00
296382        296382  2018-05-25T12:57:00.000+03:00
296396        296396  2018-05-16T18:35:00.000+03:00
296405        296405  2018-05-21T15:30:00.000+03:00
296413        296413  2018-05-09T06:57:00.000+03:00
296421        296421  2018-05-02T19:25:00.000+03:00
296427        296427  2018-05-14T15:00:00.000+03:00
296433        296433  2018-05-17T10:35:00.000+03:00
296434        296434  2018-05-02T00:37:00.000+03:00
296437        296437  2018-05-21T05:04:00.000+03:00
296449        296449  2018-05-01T23:33:00.000+03:00
296452        296452  2018-05-11T23:39:00.000+03:00
296458        296458  2018-05-18T05:33:00.000+03:00
296482        296482  2018-05-31T14:31:00.000+03:00
...              ...                            ...
305974        305974  2018-05-10T08:53:00.000+03:00
305979        305979  2018-05-07T03:00:00.000+03:00
305990        305990  2018-05-15T17:00:00.000+03:00
305995        305995  2018-05-04T00:30:00.000+03:00
306004        306004  2018-05-03T12:15:00.000+03:00
306014        306014  2018-05-23T13:45:00.000+03:00
306015        306015  2018-05-11T11:44:00.000+03:00
306016        306016  2018-05-18T03:00:00.000+03:00
306023        306023  2018-05-08T02:28:00.000+03:00
306025        306025  2018-05-01T14:09:00.000+03:00
306034        306034  2018-05-04T18:59:00.000+03:00
306036        306036  2018-05-24T08:08:00.000+03:00
306039        306039  2018-05-17T23:00:00.000+03:00
306040        306040  2018-05-15T00:05:00.000+03:00
306045        306045  2018-05-03T03:00:00.000+03:00
306050        306050  2018-05-22T07:49:00.000+03:00
306052        306052  2018-05-11T16:00:00.000+03:00
306074        306074  2018-05-09T04:05:00.000+03:00
306109        306109  2018-05-11T03:00:00.000+03:00
306115        306115  2018-05-23T03:00:00.000+03:00
306119        306119  2018-05-29T16:05:00.000+03:00
306142        306142  2018-05-17T16:34:00.000+03:00
306164        306164  2018-05-12T01:39:00.000+03:00
306167        306167  2018-05-01T03:00:00.000+03:00
306173        306173  2018-05-29T14:00:00.000+03:00
306216        306216  2018-05-23T17:53:00.000+03:00
306218        306218  2018-05-10T17:20:00.000+03:00
306219        306219  2018-05-01T09:36:00.000+03:00
306224        306224  2018-05-09T00:01:00.000+03:00
306238        306238  2018-05-10T06:17:00.000+03:00

[1372 rows x 2 columns]

In [0]:
scored_news_date = pd.merge(scored_news, test_date, left_on="Unnamed: 0", right_on = "Unnamed: 0.1")
scored_news_date.head(5)

,Unnamed: 0,title,text,Company,Industry,text_nwords,log_nword,text_no_stopwords,compound,neg,neu,pos,Unnamed: 0.1,published
0,297858,Trader sees a rally ahead for bonds,Trader sees a rally ahead for bonds 1 Hour Ago,"['E*Trade', '']",['Financials'],10,2.302585,trader sees rally ahead hour ago,0.0000,0.0,1.000,0.000,297858,2018-05-24T21:26:00.000+03:00
1,299381,White House addresses AT&T payment to Michael Cohen,White House addresses AT&T payment to Michael Cohen 17 Hours Ago,"['AT&T', '']",['Communication Services'],13,2.564949,addresses payment hours ago,0.0000,0.0,1.000,0.000,299381,2018-05-11T23:45:00.000+03:00
2,302775,BRIEF-Boston Scientific Closes NxThera Acquisition,April 30 (Reuters) - Boston Scientific Corp:\n* BOSTON SCIENTIFIC CLOSES NXTHERA ACQUISITION Source text for Eikon: Further company coverage:\n,"['Boston Scientific', '']",['Health Care'],25,3.218876,reuters scientific corp scientific closes nxthera acquisition source text eikon company coverage,0.0000,0.0,1.000,0.000,302775,2018-04-30T18:40:00.000+03:00
3,302541,GE to merge transportation unit with Wabtec,GE to merge transportation unit with Wabtec 50 Mins Ago CNBC's David Faber has the latest details on the deal between General Electric and rail equipment maker Wabtec.,"['General Electric', '']",['Industrials'],30,3.401197,ge merge transportation unit wabtec mins ago cnbc latest details general electric rail equipment maker wabtec,0.0000,0.0,1.000,0.000,302541,2018-05-21T15:42:00.000+03:00
4,302639,"BRIEF-MetLife To Provide Pension Benefits To Approximately 41,000 Fedex Retirees And Beneficiaries","May 8 (Reuters) - MetLife Inc:\n* METLIFE TO PROVIDE PENSION BENEFITS TO APPROXIMATELY 41,000 FEDEX RETIREES AND BENEFICIARIES Source text for Eikon: Further company coverage:\n","['MetLife Inc.', '']",['Financials'],31,3.433987,reuters metlife metlife provide pension benefits approximately fedex retirees beneficiaries source text eikon company coverage,0.6597,0.0,0.707,0.293,302639,2018-05-09T05:00:00.000+03:00

In [0]:
scored_news_date.columns
scored_news_date = scored_news_date[['published', 'title', 'Company', 'Industry', 'text_nwords',
 'text_no_stopwords', 'compound', 'neg', 'neu', 'pos']]

In [0]:
scored_news_date.head(3)

,published,title,Company,Industry,text_nwords,text_no_stopwords,compound,neg,neu,pos
0,2018-05-24T21:26:00.000+03:00,Trader sees a rally ahead for bonds,"['E*Trade', '']",['Financials'],10,trader sees rally ahead hour ago,0.0,0.0,1.0,0.0
1,2018-05-11T23:45:00.000+03:00,White House addresses AT&T payment to Michael Cohen,"['AT&T', '']",['Communication Services'],13,addresses payment hours ago,0.0,0.0,1.0,0.0
2,2018-04-30T18:40:00.000+03:00,BRIEF-Boston Scientific Closes NxThera Acquisition,"['Boston Scientific', '']",['Health Care'],25,reuters scientific corp scientific closes nxthera acquisition source text eikon company coverage,0.0,0.0,1.0,0.0

In [0]:
scored_news_date['published'] = pd.to_datetime(scored_news_date.published).dt.date

In [0]:
scored_news_date.head(25)

,published,title,Company,Industry,text_nwords,text_no_stopwords,compound,neg,neu,pos
0,2018-05-24,Trader sees a rally ahead for bonds,"['E*Trade', '']",['Financials'],10,trader sees rally ahead hour ago,0.0000,0.000,1.000,0.000
1,2018-05-11,White House addresses AT&T payment to Michael Cohen,"['AT&T', '']",['Communication Services'],13,addresses payment hours ago,0.0000,0.000,1.000,0.000
2,2018-04-30,BRIEF-Boston Scientific Closes NxThera Acquisition,"['Boston Scientific', '']",['Health Care'],25,reuters scientific corp scientific closes nxthera acquisition source text eikon company coverage,0.0000,0.000,1.000,0.000
3,2018-05-21,GE to merge transportation unit with Wabtec,"['General Electric', '']",['Industrials'],30,ge merge transportation unit wabtec mins ago cnbc latest details general electric rail equipment maker wabtec,0.0000,0.000,1.000,0.000
4,2018-05-09,"BRIEF-MetLife To Provide Pension Benefits To Approximately 41,000 Fedex Retirees And Beneficiaries","['MetLife Inc.', '']",['Financials'],31,reuters metlife metlife provide pension benefits approximately fedex retirees beneficiaries source text eikon company coverage,0.6597,0.000,0.707,0.293
5,2018-05-17,BRIEF-Mondelēz Declares Regular Quarterly Dividend Of $0.22 Per Share,"['Mondelez International', '']",['Consumer Staples'],31,reuters mondelez international mondelēz international declares regular dividend share source text eikon company coverage,0.2960,0.000,0.855,0.145
6,2018-05-09,Markets poised to open higher after US Iran decision,"['E*Trade', '']",['Financials'],31,markets poised open higher iran decision hours ago kamen mercadien asset management trader almanac give,0.5423,0.000,0.743,0.257
7,2018-05-24,BRIEF-Gap Inc Announces Q1 Dividend,"['Gap Inc.', '']",['Consumer Discretionary'],32,reuters gap announces dividend sets dividend share source text eikon company coverage,0.2960,0.000,0.833,0.167
8,2018-05-21,BRIEF-GE Hitachi Announces Dominion Energy As Investor In BWRX-300 Small Modular Reactor,"['General Electric', '']",['Industrials'],32,reuters general electric ge hitachi announces dominion energy investor bwrx modular reactor source text eikon company coverage,0.2732,0.000,0.884,0.116
9,2018-05-23,BRIEF-Constellation Brands Promotes Jim Sabia To Chief Marketing Officer,"['Constellation Brands', '']",['Consumer Staples'],33,reuters constellation brands constellation brands promotes sabia newly created role chief marketing officer source text eikon company coverage,0.5267,0.000,0.784,0.216
10,2018-05-18,"Campbell Soup slumps, shares are down 40%","['Campbell Soup', 'Wells Fargo', '']","['Consumer Staples', 'Financials']",34,soup slumps shares hour ago fargo securities discuss factors contributing slump consumer,0.5267,0.000,0.694,0.306
11,2018-05-04,Wells Fargo reaches deal to resolve class action suit,"['Wells Fargo', '']",['Financials'],34,fargo reaches resolve class action suit hour ago cnbc reports fargo pay part class action suit,0.3400,0.077,0.714,0.209
12,2018-05-03,BRIEF-AIG Board Declares Common Stock Dividend Of $0.32/Shr,"['American International Group', '']",['Financials'],34,reuters international group aig directors declares common dividend share source text eikon company coverage,0.2960,0.000,0.855,0.145
13,2018-05-02,BRIEF-Paychex Collaborates With Workplace By Facebook,"['Paychex Inc.', '']",['Information Technology'],34,reuters paychex paychex collaborates workplace facebook bring communication tools paychex flex users source text eikon company coverage,0.0000,0.000,1.000,0.000
14,2018-05-23,BRIEF-Alexandria Real Estate Equities Appoints Daniel Ryan As Co-Chief Investment Officer,"['Alexandria Real Estate Equities', '']",['Real Estate'],36,reuters estate equities estate equities appoints chief investment officer source text eikon company coverage,0.0000,0.000,1.000,0.000
15,2018-05-10,BRIEF-Phillips 66 Increases Quarterly Dividend By 14 Pct To $0.80 Per Share,"['Phillips 66', '']",['Energy'],36,reuters announces increase dividend increases dividend percent share source text eikon company coverage,0.5423,0.000,0.710,0.290
16,2018-05-16,Conflicting reports about Navarro's role in China talks,"['E*Trade', '']",['Financials'],36,conflicting reports role talks hour ago cnbc eamon javers reports conflicting accounts trade advisor participation trade talks,-0.6597,0.265,0.735,0.000
17,2018-05-19,"BRIEF-KCS Holds Annual Meeting Of Stockholders, Elects 12 Directors And Announces Dividends","['Kansas City Southern', '']",['Industrials'],36,reuters kcs holds meeting stockholders elects directors announces preferred common dividends source text eikon company coverage,0.0000,0.000,1.000,0.000
18,2018-05-12,A magical Disney trade,"['E*Trade', '']",['Financials'],36,magical disney trade hours ago trade management magical disney trade cnbc options action traders khouw,0.0000,0.000,1.000,0.000
19,2018-05-30,AT&T CEO: Apartment-dwelling millennials are the cord-cutters,"['AT&T', '']",['Communication Services'],37,ceo apartment dwelling millennials cord cutters mins ago ceo onstage code conference acquisition directv affected business,-0.1280,0.096,0.838,0.066
20,2018-05-23,BRIEF-Abbott Says Newest Generation Of Leading Heart Stent Now Approved In U.S. For People With Coronary Artery Disease,"['Abbott Laboratories', '']",['Health Care'],37,reuters laboratories newest generation leading heart stent approved people coronary artery disease source text eikon company coverage,0.4215,0.000,0.851,0.149
21,2018-04-30,BRIEF-CDW Holding Says Urano Koichi Retires As Chairman & CEO,"['CDW', '']",['Information Technology'],38,reuters cdw holding urano koichi retires chairman chief executive officer yoshikawa makoto promoted ceo source text eikon company coverage,0.4215,0.000,0.865,0.135
22,2018-05-09,Cramer Remix: GE just got a huge break—the stock may have bottomed,"['General Electric', '']",['Industrials'],38,remix ge huge break bottomed hours ago thinks general electric worst days recent increase oil prices,-0.1280,0.189,0.599,0.212
23,2018-05-10,"Opening Bell, May 10 2018","['MarketAxess', '']",['Financials'],38,opening hours ago ringing today opening bells axa equitable holdings chairman buberl ceo nyse marketaxess ceo nasdaq,0.0000,0.000,1.000,0.000
24,2018-05-23,BRIEF-Portland General Electric Issues Request For Proposals,"['General Electric', '']",['Industrials'],39,reuters portland general electric portland general electric issues request proposals seeking additional average megawatts renewable generating resources source text eikon company coverage,0.0000,0.000,1.000,0.000

In [0]:
scored_news_date['Industry'].nunique()

102

In [0]:
scored_news_date.Industry.unique()

array(["['Financials']", "['Communication Services']", "['Health Care']",
       "['Industrials']", "['Consumer Staples']",
       "['Consumer Discretionary']", "['Consumer Staples', 'Financials']",
       "['Information Technology']", "['Real Estate']", "['Energy']",
       "['Utilities']", "['Materials']",
       "['Consumer Discretionary', 'Financials', 'Financials']",
       "['Financials', 'Consumer Staples']",
       "['Communication Services', 'Communication Services']",
       "['Consumer Discretionary', 'Consumer Staples']",
       "['Communication Services', 'Communication Services', 'Communication Services']",
       "['Materials', 'Financials']",
       "['Information Technology', 'Financials']",
       "['Information Technology', 'Financials', 'Financials', 'Financials']",
       "['Financials', 'Financials', 'Financials']",
       "['Consumer Discretionary', 'Industrials']",
       "['Consumer Discretionary', 'Communication Services']",
       "['Consumer Staples', 'Consumer Discretionary', 'Consumer Discretionary', 'Information Technology', 'Consumer Discretionary', 'Information Technology', 'Consumer Discretionary']",
       "['Information Technology', 'Information Technology', 'Communication Services']",
       "['Consumer Staples', 'Consumer Staples', 'Consumer Discretionary']",
       "['Industrials', 'Industrials']",
       "['Information Technology', 'Information Technology']",
       "['Health Care', 'Consumer Staples']",
       "['Information Technology', 'Consumer Staples']",
       "['Communication Services', 'Communication Services', 'Information Technology']",
       "['Materials', 'Utilities']",
       "['Communication Services', 'Health Care']",
       "['Energy', 'Energy']", "['Health Care', 'Health Care']",
       "['Consumer Staples', 'Information Technology']",
       "['Industrials', 'Energy']",
       "['Financials', 'Financials', 'Financials', 'Financials']",
       "['Health Care', 'Health Care', 'Health Care']",
       "['Financials', 'Information Technology']",
       "['Industrials', 'Financials']",
       "['Communication Services', 'Consumer Discretionary']",
       "['Consumer Discretionary', 'Information Technology']",
       "['Communication Services', 'Industrials']",
       "['Consumer Discretionary', 'Financials']",
       "['Consumer Discretionary', 'Communication Services', 'Communication Services']",
       "['Financials', 'Financials']",
       "['Consumer Discretionary', 'Communication Services', 'Information Technology']",
       "['Utilities', 'Financials']",
       "['Information Technology', 'Information Technology', 'Information Technology']",
       "['Financials', 'Energy']",
       "['Consumer Discretionary', 'Consumer Discretionary']",
       "['Utilities', 'Financials', 'Information Technology']",
       "['Health Care', 'Information Technology', 'Information Technology', 'Financials']",
       "['Financials', 'Health Care', 'Financials', 'Information Technology', 'Financials']",
       "['Financials', 'Consumer Discretionary']",
       "['Financials', 'Consumer Discretionary', 'Consumer Discretionary', 'Consumer Staples']",
       "['Information Technology', 'Financials', 'Financials']",
       "['Communication Services', 'Real Estate', 'Consumer Discretionary', 'Financials']",
       "['Information Technology', 'Industrials']",
       "['Energy', 'Consumer Staples']", "['Financials', 'Industrials']",
       "['Communication Services', 'Financials']",
       "['Consumer Discretionary', 'Information Technology', 'Consumer Staples']",
       "['Information Technology', 'Financials', 'Financials', 'Information Technology']",
       "['Financials', 'Health Care']",
       "['Industrials', 'Consumer Discretionary', 'Financials', 'Communication Services']",
       "['Information Technology', 'Financials', 'Health Care', 'Health Care']",
       "['Communication Services', 'Consumer Discretionary', 'Communication Services']",
       "['Consumer Discretionary', 'Communication Services', 'Communication Services', 'Communication Services']",
       "['Financials', 'Health Care', 'Health Care']",
       "['Industrials', 'Consumer Staples', 'Health Care', 'Consumer Discretionary']",
       "['Communication Services', 'Consumer Discretionary', 'Information Technology', 'Communication Services']",
       "['Financials', 'Financials', 'Financials', 'Financials', 'Financials']",
       "['Energy', 'Financials']",
       "['Health Care', 'Health Care', 'Financials']",
       "['Financials', 'Financials', 'Financials', 'Information Technology']",
       "['Energy', 'Consumer Discretionary']",
       "['Consumer Discretionary', 'Consumer Discretionary', 'Consumer Discretionary']",
       "['Consumer Discretionary', 'Communication Services', 'Information Technology', 'Utilities', 'Industrials', 'Information Technology', 'Information Technology']",
       "['Health Care', 'Health Care', 'Consumer Staples']",
       "['Energy', 'Energy', 'Energy']",
       "['Information Technology', 'Information Technology', 'Information Technology', 'Information Technology']",
       "['Information Technology', 'Consumer Staples', 'Energy', 'Information Technology']",
       "['Consumer Discretionary', 'Industrials', 'Consumer Staples']",
       "['Communication Services', 'Financials', 'Consumer Staples']",
       "['Financials', 'Consumer Staples', 'Consumer Staples', 'Consumer Staples', 'Consumer Staples']",
       "['Financials', 'Consumer Staples', 'Consumer Staples']",
       "['Financials', 'Information Technology', 'Information Technology']",
       "['Consumer Staples', 'Financials', 'Consumer Staples', 'Materials', 'Consumer Staples']",
       "['Industrials', 'Consumer Discretionary']",
       "['Financials', 'Energy', 'Consumer Staples']",
       "['Real Estate', 'Consumer Discretionary']",
       "['Consumer Staples', 'Consumer Staples', 'Consumer Staples', 'Consumer Staples']",
       "['Financials', 'Information Technology', 'Consumer Staples', 'Financials', 'Information Technology']",
       "['Utilities', 'Utilities', 'Utilities', 'Industrials']",
       "['Utilities', 'Utilities']",
       "['Consumer Discretionary', 'Consumer Staples', 'Consumer Discretionary', 'Consumer Staples']",
       "['Consumer Staples', 'Consumer Staples']",
       "['Industrials', 'Financials', 'Consumer Staples']",
       "['Financials', 'Consumer Discretionary', 'Industrials']",
       "['Health Care', 'Financials']"], dtype=object)

In [0]:
scored_news_vader = scored_news_date

In [0]:
scored_news_vader.to_csv('scored_news_vader.csv')